"""Pull request workflow for submitting generated READMEs."""

import logging

from src.application.orchestrator import GenerationResult
from src.infrastructure.github.client import GitHubClient

logger = logging.getLogger(__name__)

__all__ = ["PRWorkflow"]


class PRWorkflow:
    """Handles the Git operations for creating a README pull request.

    Creates a new branch, commits the generated README, and opens a
    pull request against the default branch.
    """

    def __init__(self, github_client: GitHubClient) -> None:
        """Initialise the workflow.

        Args:
            github_client: GitHub API client for Git operations.
        """
        self._client = github_client

    async def create_readme_pr(self, owner: str, repo: str, result: GenerationResult) -> str:
        """Create a pull request with the generated README.

        Args:
            owner: Repository owner.
            repo: Repository name.
            result: The generation result containing README content and branch name.

        Returns:
            The URL of the created pull request.

        Raises:
            httpx.HTTPStatusError: If any GitHub API call fails.
        """
        logger.info("Creating README PR for %s/%s on branch %s", owner, repo, result.branch)

        # 1. Get default branch SHA
        default_sha = await self._client.get_default_branch_sha(owner, repo)
        logger.debug("Default branch SHA: %s", default_sha)

        # 2. Create new branch
        try:
            await self._client.create_branch(owner, repo, result.branch, default_sha)
        except Exception as exc:
            logger.warning("Branch %s may already exist: %s", result.branch, exc)

        # 3. Check if README.md already exists (to get its SHA for update)
        existing_sha: str | None = None
        try:
            existing_content = await self._client.get_file_content(owner, repo, "README.md")
            if existing_content is not None:
                # Fetch the file metadata to get the SHA
                import httpx

                token = await self._client._auth.get_installation_token(self._client._installation_id)
                async with httpx.AsyncClient() as client:
                    resp = await client.get(
                        f"{self._client.API_BASE}/repos/{owner}/{repo}/contents/README.md",
                        headers={
                            "Authorization": f"token {token}",
                            "Accept": "application/vnd.github+json",
                        },
                        params={"ref": result.branch},
                    )
                    if resp.status_code == 200:
                        existing_sha = resp.json().get("sha")
        except Exception:
            pass

        # 4. Create/update README.md on new branch
        await self._client.create_or_update_file(
            owner=owner,
            repo=repo,
            path="README.md",
            content=result.readme_content,
            message="docs: auto-generate README.md via RepoDoc AI",
            branch=result.branch,
            sha=existing_sha,
        )

        # 5. Create pull request
        sections_list = ", ".join(result.sections) if result.sections else "all"
        pr_body = (
            "## Auto-generated README\n\n"
            "This README was automatically generated by **RepoDoc AI** based on "
            "repository analysis.\n\n"
            f"**Sections included:** {sections_list}\n\n"
            f"**Tech stack detected:** {', '.join(result.tech_stack.keys()) if result.tech_stack else 'N/A'}\n\n"
            "---\n"
            "*Generated by [RepoDoc AI](https://github.com/apps/repodoc-ai)*"
        )

        pr_data = await self._client.create_pull_request(
            owner=owner,
            repo=repo,
            title="docs: update README.md (RepoDoc AI)",
            body=pr_body,
            head=result.branch,
            base="main",
        )

        pr_url = pr_data.get("html_url", "")
        logger.info("Created PR: %s", pr_url)
        return pr_url
